#!/bin/bash

INVITRO_REPO=$HOME/invitro
INVITRO_TRACE_LOCATION=$HOME/invitro-traces

SAMPLED_TRACE_LOCATION=$INVITRO_REPO/data/traces/reference
rm -rf $SAMPLED_TRACE_LOCATION
mkdir -p $SAMPLED_TRACE_LOCATION
tar -xvzf $INVITRO_TRACE_LOCATION/preprocessed_150.tar.xz -C $SAMPLED_TRACE_LOCATION
tar -xvzf $INVITRO_TRACE_LOCATION/sampled_150.tar.xz -C $SAMPLED_TRACE_LOCATION

AZURE_TRACE_LOCATION=$INVITRO_REPO/data/azure
rm -rf $AZURE_TRACE_LOCATION
mkdir -p $AZURE_TRACE_LOCATION
tar -xvzf $INVITRO_TRACE_LOCATION/azurefunctions-dataset2019.tar.xz -C $AZURE_TRACE_LOCATION

