apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aes-go-1000000-1010000-y6hjru1
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=aes-go
        - --value=10
        - --generator=random
        - --lowerBound=1000000
        - --upperBound=1010000
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0:50051
        image: docker.io/vhiveease/aes-go:latest
