
output-files-path: /users/ArunAMS/vSwarm/tools/load-generator/expt/aes-go-1000000-1010000-200
log-files-path: /users/ArunAMS/vSwarm/tools/load-generator/expt/aes-go-1000000-1010000-200

load-generator:
  deploy: true
  python_file: /users/ArunAMS/vSwarm/tools/load-generator/main.py
  load_json: /users/ArunAMS/vSwarm/tools/load-generator/load.json
  trace_path: /users/ArunAMS/vSwarm/tools/load-generator/200
  profile_json: /users/ArunAMS/vSwarm/tools/load-generator/profile.json
  config_json: /users/ArunAMS/vSwarm/tools/load-generator/config.json
  build_path: /users/ArunAMS/vSwarm/tools/load-generator/build
  expt_dur: 9
  warmup_dur: 2

invoke-load:
  run: true
  binary_path: /users/ArunAMS/vSwarm/tools/load-generator/invoker
  log_file: invoker-load.log
  expt_dur: 9
  warmup_dur: 2

profile-service:
  deploy: true
  yaml_path: /users/ArunAMS/vSwarm/tools/load-generator/yamls/aes-go/kn-aes-go-1000000-1010000.yaml
  predeployment_commands: []
  postdeployment_commands: []
  endpoints_file: endpoints.json  

invoke-service:
  run: true
  binary_path: .
  log_file: invoker-service.log
  dur_file: dur.txt
  lat_file: lat.txt
  expt_dur: 11
  rps: 0.2

taskset-service:
  set: true
  cpuid: 2

perf:
  collect: true
  grep_string: "/app/server"
  event_list:
    - CPU_CLK_UNHALTED.THREAD
    - INST_RETIRED.ANY
    - L2_RQSTS.MISS
    - L2_RQSTS.REFERENCES
    - CYCLE_ACTIVITY.CYCLES_L2_MISS
    - CYCLE_ACTIVITY.CYCLES_L3_MISS
    - CYCLE_ACTIVITY.CYCLES_MEM_ANY

  expt_dur: 8
  warmup_dur: 2
  output_file: perf.txt

mpstat:
  collect: true
  expt_dur: 8
  warmup_dur: 2
  interval: 60
  output_file: mpstat.txt
