apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aes-nodejs-100000-101000-yyfsbmr
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=aes-nodejs
        - --value=10
        - --generator=random
        - --lowerBound=100000
        - --upperBound=101000
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0
        - --port=50051
        image: docker.io/vhiveease/aes-nodejs:latest
