apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aes-python-200000-202000-ktq5lxd
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=aes-python
        - --value=10
        - --generator=random
        - --lowerBound=200000
        - --upperBound=202000
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0
        - --port=50051
        image: docker.io/vhiveease/aes-python:latest
