apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-python-20000-20200-lrqr1eb
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=fibonacci-python
        - --value=10
        - --generator=random
        - --lowerBound=20000
        - --upperBound=20200
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0
        - --port=50051
        image: docker.io/vhiveease/fibonacci-python-mod:latest
