apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-analytics-standalone-python-10-x42rsrp
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=video-analytics-standalone-python
        - --value=video1.mp4
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0
        - --port=50051
        - --db_addr=mongodb://video-analytics-standalone-database:27017
        - --default_video=default.mp4
        - --num_frames=10
        image: docker.io/vhiveease/video-analytics-standalone-python:latest
