apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-go-70000-70700-gldozhi
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=fibonacci-go
        - --value=10
        - --generator=random
        - --lowerBound=70000
        - --upperBound=70700
        - --profile-function=true
        image: docker.io/vhiveease/relay-latency:latest
        ports:
        - containerPort: 50000
          name: h2c
      - args:
        - --addr=0.0.0.0:50051
        image: docker.io/vhiveease/fibonacci-go-mod:latest
