
output-files-path: /users/Lakshman/vSwarm/tools/load-generator/expt/aes-nodejs-700000-707000-900
log-files-path: /users/Lakshman/vSwarm/tools/load-generator/expt/aes-nodejs-700000-707000-900

load-generator:
  deploy: true
  python_file: /users/Lakshman/vSwarm/tools/load-generator/main.py
  load_json: /users/Lakshman/vSwarm/tools/load-generator/load.json
  trace_path: /users/Lakshman/vSwarm/tools/load-generator/900
  profile_json: /users/Lakshman/vSwarm/tools/load-generator/profile.json
  config_json: /users/Lakshman/vSwarm/tools/load-generator/config.json
  build_path: /users/Lakshman/vSwarm/tools/load-generator/build
  expt_dur: 4
  warmup_dur: 1

invoke-load:
  run: true
  binary_path: /users/Lakshman/vSwarm/tools/load-generator/invoker
  log_file: invoker-load.log
  expt_dur: 4
  warmup_dur: 1

profile-service:
  deploy: false
  yaml_path: /users/Lakshman/vSwarm/tools/load-generator/yamls/aes-nodejs/kn-aes-nodejs-700000-707000.yaml
  predeployment_commands: []
  postdeployment_commands: []
  endpoints_file: endpoints.json  

invoke-service:
  run: false
  binary_path: .
  log_file: invoker-service.log
  dur_file: dur.txt
  lat_file: lat.txt
  expt_dur: 5
  rps: 0.2

taskset-service:
  set: false
  cpuid: 2

perf:
  collect: false
  grep_string: "/app/server"
  event_list:
    - CPU_CLK_UNHALTED.THREAD
    - INST_RETIRED.ANY

  expt_dur: 3
  interval_print_ms: 500
  warmup_dur: 1
  output_file: perf.txt

mpstat:
  collect: true
  expt_dur: 3
  warmup_dur: 1
  interval: 60
  output_file: mpstat.txt
