
output-files-path: /users/Lakshman/vSwarm/tools/load-generator/expt/image-rotate-go-3-10
log-files-path: /users/Lakshman/vSwarm/tools/load-generator/expt/image-rotate-go-3-10

load-generator:
  deploy: false
  python_file: /users/Lakshman/vSwarm/tools/load-generator/main.py
  load_json: /users/Lakshman/vSwarm/tools/load-generator/load.json
  trace_path: /users/Lakshman/vSwarm/tools/load-generator/10
  profile_json: /users/Lakshman/vSwarm/tools/load-generator/profile.json
  config_json: /users/Lakshman/vSwarm/tools/load-generator/config.json
  build_path: /users/Lakshman/vSwarm/tools/load-generator/build
  expt_dur: 4
  warmup_dur: 1

invoke-load:
  run: true
  binary_path: /users/Lakshman/vSwarm/tools/load-generator/invoker
  log_file: invoker-load.log
  expt_dur: 4
  warmup_dur: 1

profile-service:
  deploy: true
  yaml_path: /users/Lakshman/vSwarm/tools/load-generator/yamls/image-rotate-go/kn-image-rotate-go-3.yaml
  predeployment_commands: [kubectl apply -f /users/Lakshman/vSwarm/tools/load-generator/yamls/image-rotate-go/image-rotate-database.yaml]
  postdeployment_commands: []
  endpoints_file: endpoints.json  

invoke-service:
  run: true
  binary_path: .
  log_file: invoker-service.log
  dur_file: dur.txt
  lat_file: lat.txt
  expt_dur: 5
  rps: 0.2

taskset-service:
  set: true
  cpuid: 2

perf:
  collect: true
  grep_string: "python3 /app/server.py"
  event_list:
    - CPU_CLK_UNHALTED.THREAD
    - INST_RETIRED.ANY

  expt_dur: 3
  interval_print_ms: 500
  warmup_dur: 1
  output_file: perf.txt

mpstat:
  collect: true
  expt_dur: 3
  warmup_dur: 1
  interval: 60
  output_file: mpstat.txt
